// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6VgKBt4hi19tGSyoMs5NFZdmthYROew',
    appId: '1:112265753690:web:489aaad13a286d31835463',
    messagingSenderId: '112265753690',
    projectId: 'ti-pagi-14',
    authDomain: 'ti-pagi-14.firebaseapp.com',
    storageBucket: 'ti-pagi-14.firebasestorage.app',
    measurementId: 'G-JYME8G7Y5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXWLJuJgOYI68ROhaitnmEh3MhbphQsI',
    appId: '1:112265753690:android:ba5e435549ee2f9d835463',
    messagingSenderId: '112265753690',
    projectId: 'ti-pagi-14',
    storageBucket: 'ti-pagi-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvMERitAwiJQooWooEVt8ZJEJrnXwyfo',
    appId: '1:112265753690:ios:c0a0346de045e1ca835463',
    messagingSenderId: '112265753690',
    projectId: 'ti-pagi-14',
    storageBucket: 'ti-pagi-14.firebasestorage.app',
    iosBundleId: 'com.example.flutterSore12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuvMERitAwiJQooWooEVt8ZJEJrnXwyfo',
    appId: '1:112265753690:ios:c0a0346de045e1ca835463',
    messagingSenderId: '112265753690',
    projectId: 'ti-pagi-14',
    storageBucket: 'ti-pagi-14.firebasestorage.app',
    iosBundleId: 'com.example.flutterSore12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO6VgKBt4hi19tGSyoMs5NFZdmthYROew',
    appId: '1:112265753690:web:72d38d561b51ff16835463',
    messagingSenderId: '112265753690',
    projectId: 'ti-pagi-14',
    authDomain: 'ti-pagi-14.firebaseapp.com',
    storageBucket: 'ti-pagi-14.firebasestorage.app',
    measurementId: 'G-Q6JKDQZXP2',
  );
}
