// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQs6Gn7oa4m7O5nLn0_qFg0Xs6kNAjGOo',
    appId: '1:1002121929422:web:86a388da6bb1ad08a8669f',
    messagingSenderId: '1002121929422',
    projectId: 'ti-pertemuan-14-22b78',
    authDomain: 'ti-pertemuan-14-22b78.firebaseapp.com',
    storageBucket: 'ti-pertemuan-14-22b78.firebasestorage.app',
    measurementId: 'G-LT2406T1D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__1wKlKJeciBFGMdgv_jyizB962awpCo',
    appId: '1:1002121929422:android:e4677072bbf8ef74a8669f',
    messagingSenderId: '1002121929422',
    projectId: 'ti-pertemuan-14-22b78',
    storageBucket: 'ti-pertemuan-14-22b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqXdsDBd7M_B3JkcWzhWhVM030qVRdGY',
    appId: '1:1002121929422:ios:1544cf5f70cafa4fa8669f',
    messagingSenderId: '1002121929422',
    projectId: 'ti-pertemuan-14-22b78',
    storageBucket: 'ti-pertemuan-14-22b78.firebasestorage.app',
    iosBundleId: 'com.example.flutterSore12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqXdsDBd7M_B3JkcWzhWhVM030qVRdGY',
    appId: '1:1002121929422:ios:1544cf5f70cafa4fa8669f',
    messagingSenderId: '1002121929422',
    projectId: 'ti-pertemuan-14-22b78',
    storageBucket: 'ti-pertemuan-14-22b78.firebasestorage.app',
    iosBundleId: 'com.example.flutterSore12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQs6Gn7oa4m7O5nLn0_qFg0Xs6kNAjGOo',
    appId: '1:1002121929422:web:7d08b79db27b29d7a8669f',
    messagingSenderId: '1002121929422',
    projectId: 'ti-pertemuan-14-22b78',
    authDomain: 'ti-pertemuan-14-22b78.firebaseapp.com',
    storageBucket: 'ti-pertemuan-14-22b78.firebasestorage.app',
    measurementId: 'G-KS03RXVT4D',
  );
}
